consumer_1:
  env: broker3:9092,broker2:9093,broker1:9091
  consumer_group: test_group
  message_topic: orders 


http_server:
  host: localhost
  protocol: http
  port: 8000
  timeout: 5s
  idle_timeout: 60s