#opt/kafka/bin/kafka-topics.sh --create --topic orders --bootstrap-server localhost:29092 --replication-factor 2 --partitions 3

version: "3.9"
services:
  broker1:
    image: apache/kafka:latest
    hostname: broker1
    container_name: broker1
    ports:
      - 9092:9092  # Map PLAINTEXT_HOST to the host
      - 29094:29094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://broker1:29094,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29092,PLAINTEXT_HOST://localhost:9092,CONTROLLER://broker1:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:29094,2@broker2:29096,3@broker3:29095
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_KRAFT_CLUSTER_ID: "${CLUSTER_ID:-$(uuidgen)}"
    networks:
      - kafka-network
    volumes:
      - kafka_data1:/kafka/data

  broker2:
    image: apache/kafka:latest
    hostname: broker2
    container_name: broker2
    ports:
      - 9093:9093  # Map PLAINTEXT_HOST to the host
      - 29096:29096
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29093,CONTROLLER://broker2:29096,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:29093,PLAINTEXT_HOST://localhost:9093,CONTROLLER://broker2:29096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:29094,2@broker2:29096,3@broker3:29095
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_KRAFT_CLUSTER_ID: "${CLUSTER_ID:-$(uuidgen)}"
    networks:
      - kafka-network
    volumes:
      - kafka_data2:/kafka/data

  broker3:
    image: apache/kafka:latest
    hostname: broker3
    container_name: broker3
    ports:
      - 9094:9094  # Map PLAINTEXT_HOST to the host
      - 29095:29095
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29094,CONTROLLER://broker3:29095,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:29094,PLAINTEXT_HOST://localhost:9094,CONTROLLER://broker3:29095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:29094,2@broker2:29096,3@broker3:29095
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_KRAFT_CLUSTER_ID: "${CLUSTER_ID:-$(uuidgen)}"
    networks:
      - kafka-network
    volumes:
      - kafka_data3:/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9020:8080"  # Порт для доступа к Kafka UI
    environment:
      KAFKA_CLUSTERS_0_NAME: postgres_connect_01
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "broker1:29092,broker2:29093,broker3:29091"
    depends_on:
      - broker1
      - broker2
      - broker3
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9020/actuator/health"] #лучше использовать curl, но его нужно устанавливать в образ
      interval: 10s
      timeout: 3s
      retries: 2

networks:
  kafka-network:
    driver: bridge

volumes:
  kafka_data1:
  kafka_data2:
  kafka_data3: