services:
#  app:
#    build: .
#    image: mp3Player
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/deliveries
#      SPRING_DATASOURCE_USERNAME: myuser
#      SPRING_DATASOURCE_PASSWORD: mypassword
#    depends_on:
#      db:
#        condition: service_healthy
#    networks:
#      - network
  db:
    image: postgres:latest
    container_name: users_db
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network
volumes:
  postgres_data:

networks:
  network:
    driver: bridge