services:
  registration_service:
    build: ./User_for_image-board_Service
    ports:
      - "8001:8001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/users_db
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth_net
  
  auth:
    build: ./Auth_for_image_board
    ports:
      - "8002:8002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/users_db
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth_net  
      
  db:
    image: postgres:latest
    container_name: users_db
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auth_net
volumes:
  postgres_data:

networks:
  auth_net:
    name: auth_net
    driver: bridge