networks:
  consumer_and_produser_network:
    external: true
services:
  # consumer:
  #   image: consumer:latest
  #   # build:
  #   #   context: consumer_and_Produser 
  #   #   dockerfile:  Dockerfile.consumer
  #   command: ./consumer
  #   networks:
  #     - consumer_and_produser_network
  #   volumes:
  #     - ./logs:/app/logs
  #   working_dir: /app
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./consumer&Produser/config/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - consumer_and_produser_network

volumes:
  postgres_data:
