version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5430:5430"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./consumer&Produser/config/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork: