containers:
	cd consumer_and_Produser/ && cd cmd/consumer/
	go build -o consumer_conteiner main.go

#  docker build -t sinchron -f  Dockerfile.sinchron .
#  docker-compose logs -f sinchron
#  docker network inspect consumer_and_produser_kafka-network